<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OeEaNBc' shared service.

return $this->privates['.service_locator.OeEaNBc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'priceGrid' => ['privates', '.errored..service_locator.OeEaNBc.App\\Entity\\PriceGrid', NULL, 'Cannot autowire service ".service_locator.OeEaNBc": it references class "App\\Entity\\PriceGrid" but no such service exists.'],
]);
