<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dAblg0c' shared service.

return $this->privates['.service_locator.dAblg0c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'sponsor' => ['privates', '.errored..service_locator.dAblg0c.App\\Entity\\Sponsor', NULL, 'Cannot autowire service ".service_locator.dAblg0c": it references class "App\\Entity\\Sponsor" but no such service exists.'],
]);
