<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wQ0s3ra' shared service.

return $this->privates['.service_locator.wQ0s3ra'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paiement' => ['privates', '.errored..service_locator.wQ0s3ra.App\\Entity\\Paiement', NULL, 'Cannot autowire service ".service_locator.wQ0s3ra": it references class "App\\Entity\\Paiement" but no such service exists.'],
]);
