<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..ls7Tau' shared service.

return $this->privates['.service_locator..ls7Tau'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adress' => ['privates', '.errored..service_locator..ls7Tau.App\\Entity\\Adress', NULL, 'Cannot autowire service ".service_locator..ls7Tau": it references class "App\\Entity\\Adress" but no such service exists.'],
    'city' => ['privates', '.errored..service_locator..ls7Tau.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator..ls7Tau": it references class "App\\Entity\\City" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'usr' => ['privates', '.errored..service_locator..ls7Tau.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator..ls7Tau": it references class "App\\Entity\\User" but no such service exists.'],
]);
