<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.chlmFXi' shared service.

return $this->privates['.service_locator.chlmFXi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contentPage' => ['privates', '.errored..service_locator.chlmFXi.App\\Entity\\ContentPage', NULL, 'Cannot autowire service ".service_locator.chlmFXi": it references class "App\\Entity\\ContentPage" but no such service exists.'],
    'galleryRepo' => ['privates', 'App\\Repository\\GalleryRepository', 'getGalleryRepositoryService.php', true],
    'repoArticle' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'repoEvent' => ['privates', 'App\\Repository\\VikaEventRepository', 'getVikaEventRepositoryService.php', true],
    'repoSponsor' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService.php', true],
]);
