<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.S99DS4p' shared service.

return $this->privates['.service_locator.S99DS4p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'vikaEventRepository' => ['privates', 'App\\Repository\\VikaEventRepository', 'getVikaEventRepositoryService.php', true],
]);
