<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VflJ1yE' shared service.

return $this->privates['.service_locator.VflJ1yE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'usr' => ['privates', '.errored..service_locator.VflJ1yE.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.VflJ1yE": it references class "App\\Entity\\User" but no such service exists.'],
]);
