<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JfznA1X' shared service.

return $this->privates['.service_locator.JfznA1X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contentPage' => ['privates', '.errored..service_locator.JfznA1X.App\\Entity\\ContentPage', NULL, 'Cannot autowire service ".service_locator.JfznA1X": it references class "App\\Entity\\ContentPage" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\EncadrementRepository', 'getEncadrementRepositoryService.php', true],
]);
