<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3Z7.bO6' shared service.

return $this->privates['.service_locator.3Z7.bO6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contentPage' => ['privates', '.errored..service_locator.3Z7.bO6.App\\Entity\\ContentPage', NULL, 'Cannot autowire service ".service_locator.3Z7.bO6": it references class "App\\Entity\\ContentPage" but no such service exists.'],
]);
