<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T4kZ1XL' shared service.

return $this->privates['.service_locator.T4kZ1XL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'PoC' => ['privates', '.errored..service_locator.T4kZ1XL.App\\Entity\\PersonOfContact', NULL, 'Cannot autowire service ".service_locator.T4kZ1XL": it references class "App\\Entity\\PersonOfContact" but no such service exists.'],
    'contactList' => ['privates', '.errored..service_locator.T4kZ1XL.App\\Entity\\ContactList', NULL, 'Cannot autowire service ".service_locator.T4kZ1XL": it references class "App\\Entity\\ContactList" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'usr' => ['privates', '.errored..service_locator.T4kZ1XL.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.T4kZ1XL": it references class "App\\Entity\\User" but no such service exists.'],
]);
