<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ANa2w2J' shared service.

return $this->privates['.service_locator.ANa2w2J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userConnected' => ['privates', '.errored..service_locator.ANa2w2J.App\\Entity\\UserConnected', NULL, 'Cannot autowire service ".service_locator.ANa2w2J": it references class "App\\Entity\\UserConnected" but no such service exists.'],
]);
