<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NfDU_kR' shared service.

return $this->privates['.service_locator.NfDU_kR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'usr' => ['privates', '.errored..service_locator.NfDU_kR.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.NfDU_kR": it references class "App\\Entity\\User" but no such service exists.'],
]);
