<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2GKesLi' shared service.

return $this->privates['.service_locator.2GKesLi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authChecker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'userConnected' => ['privates', '.errored..service_locator.2GKesLi.App\\Entity\\UserConnected', NULL, 'Cannot autowire service ".service_locator.2GKesLi": it references class "App\\Entity\\UserConnected" but no such service exists.'],
]);
