<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hVq2lHN' shared service.

return $this->privates['.service_locator.hVq2lHN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repoRegistration' => ['privates', 'App\\Repository\\RegistrationRepository', 'getRegistrationRepositoryService.php', true],
]);
