<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aD8lwsE' shared service.

return $this->privates['.service_locator.aD8lwsE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'registration' => ['privates', '.errored..service_locator.aD8lwsE.App\\Entity\\Registration', NULL, 'Cannot autowire service ".service_locator.aD8lwsE": it references class "App\\Entity\\Registration" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService.php', true],
]);
