<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.IPxB2LO.App\Entity\Paiement' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Paiement.php';

return $this->privates['.errored..service_locator.IPxB2LO.App\Entity\Paiement'] = new \App\Entity\Paiement();
