<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.25_oYi2.App\Entity\Phone' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Phone.php';

return $this->privates['.errored..service_locator.25_oYi2.App\Entity\Phone'] = new \App\Entity\Phone();
