<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XDqn5l5' shared service.

return $this->privates['.service_locator.XDqn5l5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'content' => ['privates', '.errored..service_locator.XDqn5l5.App\\Entity\\ContentPage', NULL, 'Cannot autowire service ".service_locator.XDqn5l5": it references class "App\\Entity\\ContentPage" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
]);
