<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tG_H7pf' shared service.

return $this->privates['.service_locator.tG_H7pf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contentPage' => ['privates', '.errored..service_locator.tG_H7pf.App\\Entity\\ContentPage', NULL, 'Cannot autowire service ".service_locator.tG_H7pf": it references class "App\\Entity\\ContentPage" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService.php', true],
]);
