<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ATsVI81' shared service.

return $this->privates['.service_locator.ATsVI81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'usr' => ['privates', '.errored..service_locator.ATsVI81.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.ATsVI81": it references class "App\\Entity\\User" but no such service exists.'],
]);
