<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X.ItyKH' shared service.

return $this->privates['.service_locator.X.ItyKH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doc' => ['privates', '.errored..service_locator.X.ItyKH.App\\Entity\\AttachedFile', NULL, 'Cannot autowire service ".service_locator.X.ItyKH": it references class "App\\Entity\\AttachedFile" but no such service exists.'],
]);
