<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DeBj0Ok' shared service.

return $this->privates['.service_locator.DeBj0Ok'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'personne' => ['privates', '.errored..service_locator.DeBj0Ok.App\\Entity\\Encadrement', NULL, 'Cannot autowire service ".service_locator.DeBj0Ok": it references class "App\\Entity\\Encadrement" but no such service exists.'],
]);
