<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cJ7DpVm' shared service.

return $this->privates['.service_locator.cJ7DpVm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authChecker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'usr' => ['privates', '.errored..service_locator.cJ7DpVm.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.cJ7DpVm": it references class "App\\Entity\\User" but no such service exists.'],
]);
