<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.25_oYi2' shared service.

return $this->privates['.service_locator.25_oYi2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'phone' => ['privates', '.errored..service_locator.25_oYi2.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.25_oYi2": it references class "App\\Entity\\Phone" but no such service exists.'],
    'usr' => ['privates', '.errored..service_locator.25_oYi2.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.25_oYi2": it references class "App\\Entity\\User" but no such service exists.'],
]);
