<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tuUx0ww' shared service.

return $this->privates['.service_locator.tuUx0ww'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'newRegistration' => ['privates', '.errored..service_locator.tuUx0ww.App\\Entity\\Registration', NULL, 'Cannot autowire service ".service_locator.tuUx0ww": it references class "App\\Entity\\Registration" but no such service exists.'],
    'usr' => ['privates', '.errored..service_locator.tuUx0ww.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.tuUx0ww": it references class "App\\Entity\\User" but no such service exists.'],
]);
