<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zvx0i3e' shared service.

return $this->privates['.service_locator.zvx0i3e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'galerie' => ['privates', '.errored..service_locator.zvx0i3e.App\\Entity\\Gallery', NULL, 'Cannot autowire service ".service_locator.zvx0i3e": it references class "App\\Entity\\Gallery" but no such service exists.'],
]);
