<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eze54CO' shared service.

return $this->privates['.service_locator.eze54CO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'history' => ['privates', '.errored..service_locator.eze54CO.App\\Entity\\History', NULL, 'Cannot autowire service ".service_locator.eze54CO": it references class "App\\Entity\\History" but no such service exists.'],
]);
