<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistry.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\DependencyInjection\\DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\DataCollector\\Proxy\\ResolvedTypeFactoryDataCollectorProxy.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Form\\AddUserType' => ['privates', 'App\\Form\\AddUserType', 'getAddUserTypeService.php', true],
    'App\\Form\\AdressType' => ['privates', 'App\\Form\\AdressType', 'getAdressTypeService.php', true],
    'App\\Form\\ArticleType' => ['privates', 'App\\Form\\ArticleType', 'getArticleTypeService.php', true],
    'App\\Form\\CityType' => ['privates', 'App\\Form\\CityType', 'getCityTypeService.php', true],
    'App\\Form\\CommentType' => ['privates', 'App\\Form\\CommentType', 'getCommentTypeService.php', true],
    'App\\Form\\ContactClubType' => ['privates', 'App\\Form\\ContactClubType', 'getContactClubTypeService.php', true],
    'App\\Form\\ContactListType' => ['privates', 'App\\Form\\ContactListType', 'getContactListTypeService.php', true],
    'App\\Form\\ContentType' => ['privates', 'App\\Form\\ContentType', 'getContentTypeService.php', true],
    'App\\Form\\DocumentForReg2Type' => ['privates', 'App\\Form\\DocumentForReg2Type', 'getDocumentForReg2TypeService.php', true],
    'App\\Form\\DocumentForRegType' => ['privates', 'App\\Form\\DocumentForRegType', 'getDocumentForRegTypeService.php', true],
    'App\\Form\\DocumentType' => ['privates', 'App\\Form\\DocumentType', 'getDocumentTypeService.php', true],
    'App\\Form\\EncadrementType' => ['privates', 'App\\Form\\EncadrementType', 'getEncadrementTypeService.php', true],
    'App\\Form\\GalleryHomeType' => ['privates', 'App\\Form\\GalleryHomeType', 'getGalleryHomeTypeService.php', true],
    'App\\Form\\GalleryType' => ['privates', 'App\\Form\\GalleryType', 'getGalleryTypeService.php', true],
    'App\\Form\\HistoryType' => ['privates', 'App\\Form\\HistoryType', 'getHistoryTypeService.php', true],
    'App\\Form\\MediaType' => ['privates', 'App\\Form\\MediaType', 'getMediaTypeService.php', true],
    'App\\Form\\NotificationType' => ['privates', 'App\\Form\\NotificationType', 'getNotificationTypeService.php', true],
    'App\\Form\\PaiementManagementType' => ['privates', 'App\\Form\\PaiementManagementType', 'getPaiementManagementTypeService.php', true],
    'App\\Form\\PaiementType' => ['privates', 'App\\Form\\PaiementType', 'getPaiementTypeService.php', true],
    'App\\Form\\PersonOfContactType' => ['privates', 'App\\Form\\PersonOfContactType', 'getPersonOfContactTypeService.php', true],
    'App\\Form\\PhoneType' => ['privates', 'App\\Form\\PhoneType', 'getPhoneTypeService.php', true],
    'App\\Form\\PreregistrationType' => ['privates', 'App\\Form\\PreregistrationType', 'getPreregistrationTypeService.php', true],
    'App\\Form\\PriceGridType' => ['privates', 'App\\Form\\PriceGridType', 'getPriceGridTypeService.php', true],
    'App\\Form\\RegistrationRemarkType' => ['privates', 'App\\Form\\RegistrationRemarkType', 'getRegistrationRemarkTypeService.php', true],
    'App\\Form\\RegistrationType' => ['privates', 'App\\Form\\RegistrationType', 'getRegistrationTypeService.php', true],
    'App\\Form\\ResetPasswordType' => ['privates', 'App\\Form\\ResetPasswordType', 'getResetPasswordTypeService.php', true],
    'App\\Form\\SponsorType' => ['privates', 'App\\Form\\SponsorType', 'getSponsorTypeService.php', true],
    'App\\Form\\UserForRegType' => ['privates', 'App\\Form\\UserForRegType', 'getUserForRegTypeService.php', true],
    'App\\Form\\UserPictureType' => ['privates', 'App\\Form\\UserPictureType', 'getUserPictureTypeService.php', true],
    'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService.php', true],
    'App\\Form\\VikaEventType' => ['privates', 'App\\Form\\VikaEventType', 'getVikaEventTypeService.php', true],
    'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType' => ['privates', 'fos_ck_editor.form.type', 'getFosCkEditor_Form_TypeService.php', true],
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
    'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => ['services', 'vich_uploader.form.type.file', 'getVichUploader_Form_Type_FileService.php', true],
    'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => ['services', 'vich_uploader.form.type.image', 'getVichUploader_Form_Type_ImageService.php', true],
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => ($this->privates['form.type_extension.form.data_collector'] ?? $this->load('getForm_TypeExtension_Form_DataCollectorService.php'));
}, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($this->privates['data_collector.form'] ?? $this->getDataCollector_FormService())));
