<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.zvx0i3e.App\Entity\Gallery' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Gallery.php';

return $this->privates['.errored..service_locator.zvx0i3e.App\Entity\Gallery'] = new \App\Entity\Gallery();
