<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'onurb_yuml.client' shared service.

include_once $this->targetDirs[3].'\\vendor\\onurb\\doctrine-yuml-bundle\\lib\\Onurb\\Bundle\\YumlBundle\\Yuml\\YumlClientInterface.php';
include_once $this->targetDirs[3].'\\vendor\\onurb\\doctrine-yuml-bundle\\lib\\Onurb\\Bundle\\YumlBundle\\Yuml\\YumlClient.php';

return $this->services['onurb_yuml.client'] = new \Onurb\Bundle\YumlBundle\Yuml\YumlClient(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
