<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Onurb\Bundle\YumlBundle\Command\YumlCommand' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Command\\ContainerAwareCommand.php';
include_once $this->targetDirs[3].'\\vendor\\onurb\\doctrine-yuml-bundle\\lib\\Onurb\\Bundle\\YumlBundle\\Command\\YumlCommand.php';

$this->privates['Onurb\Bundle\YumlBundle\Command\YumlCommand'] = $instance = new \Onurb\Bundle\YumlBundle\Command\YumlCommand();

$instance->setName('yuml:mappings');

return $instance;
