<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQmbsnx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQmbsnx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQmbsnx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQmbsnx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRQmbsnx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RQmbsnx',
    'container.build_id' => 'cc8c2cec',
    'container.build_time' => 1558269066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQmbsnx');
